name: Build & Test MKDocs

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Build Docker image
        run: |
          docker build -t mkdocs_local .
      # Runs a set of commands using the runners shell
      - name: Test Produce
        run: |
          docker run -d -v "$(pwd)/projects":/projects mkdocs_local produce
          sleep 10
          ls -lah $(pwd)/projects
      - name: Test Serve
        run: |          
          docker run -p 8000:8000 -v "$(pwd)/projects":/projects mkdocs_local serve
          sleep 10
          curl -sSLi http://127.0.0.1:8000  | grep '200 OK'
